DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE game (
  id INTEGER PRIMARY KEY,
  top INTEGER NOT NULL,
  jungle INTEGER NOT NULL,
  mid INTEGER NOT NULL,
  adc INTEGER NOT NULL,
  support INTEGER NOT NULL,
  enemy_top INTEGER NOT NULL,
  enemy_jungle INTEGER NOT NULL,
  enemy_mid INTEGER NOT NULL,
  enemy_adc INTEGER NOT NULL,
  enemy_support INTEGER NOT NULL,
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);